In [2]:
# Library Packages 
#%run libraries.py 
from __future__ import division
#from tsfresh import extract_features
import pandas as pd
import numpy as np
# Settings 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
seed = 7
np.random.seed(seed)

import warnings
warnings.filterwarnings('ignore')

def front(self, n):
    return self.iloc[:, :n]

def back(self, n):
    return self.iloc[:, -n:]

# Like normalization, standardization can be useful, and even required in some
# machine learning algorithms when your time series data has input values with differing scales.


from sklearn.preprocessing import StandardScaler

def Standardisation(df):
    listed = list(df)
    scaler = StandardScaler()
    scaled = scaler.fit_transform(df)
    df = pd.DataFrame(scaled)
    df.columns = listed
    return df



np.set_printoptions(threshold=np.nan)

!free -h

'free' is not recognized as an internal or external command,
operable program or batch file.

In [11]:

gp = "E:\DS\Bankruptcy\Bankrupt\Data"

rat = pd.read_excel(gp+"\Trackers\\ratio_tracker.xlsx")
act = pd.read_excel(gp+"\Trackers\\acc_tracker.xlsx")

act = act[["Variable Name","Variable Description","Category"]]
rat = rat[["Variable Name","Financial Ratio","Category"]]
rat["Variable Description"] = rat["Financial Ratio"]
rat.drop("Financial Ratio",axis=1, inplace=True)

act["Type"] = "Fixed Value"
rat["Type"] = "Ratio"

ract = pd.concat((act,rat),axis=0).reset_index(drop=True)
ract["Period"] = "Fixed Period"

#ract.loc[ract.shape[0]+1] = ["optprcey","Options Outstanding End of Year - Price"]
#ract.loc[ract.shape[0]+1] = ["stkco","Stock Compensation Expense"]
#ract.loc[ract.shape[0]+1] = ["xintopt","Implied Option Expense"]

ract_pct = pd.DataFrame()
ract_pct["Variable Name"] = ract["Variable Name"].apply(lambda x: x+"_prtc" )
ract_pct["Variable Description"] = ract["Variable Description"].apply(lambda x: "% Change in "+x)
ract_pct["Category"] = ract["Category"]
ract_pct["Type"] = ract["Type"]
ract_pct["Period"] = "% Change"

blackt = pd.concat((ract,ract_pct),axis=0)

In [33]:
#  Reading in Bankrupt

#### You would have to download new data for the new dataset. 
## Each of the three types

fsmall = pd.read_csv(gp+"/Fixer/fixer_bankrupt.csv")

fbig = pd.read_csv(gp+"/Fixed/fixed_bankrupt.csv")

fcon = pd.merge(fsmall, fbig, on=["tic","datadate"], how="left")

frat = pd.read_csv(gp+"/Ratio/ratio_bankrupt.csv")

rat_fin = pd.merge(frat, fcon, left_on=["public_date","gvkey"], right_on=["datadate","gvkey_x"], how="left")

len(rat_fin["gvkey_x"].unique())

rat_fin_1 = rat_fin[~rat_fin["gvkey_x"].isnull()]

bank_dp = pd.read_excel(gp+"/DataFrame/Merged_3.xlsx")

bank_dp = bank_dp.drop_duplicates("Ticker",keep="first")

bank_dp  = bank_dp[~bank_dp["Ticker"].isnull()]

In [ ]:
## Old

In [14]:
bank_dp.head()

,Debtor Firms,Companies,Ticker,Industry Division,Industry Group,Cause,Date Filed,Disposition,ยง363 Sale,Duration,Inc. State,District Filed,City Filed,Forum Shopping,Filing Party,Plan Type,Employees,Business Survival,Refiled,Headquarters City,Region,City,Date Disposed,Asset Size,Employee Size,Annual Sales,Assets (millions),Chapter at Filing,Debtor's Attorney
0,New Century Communications Inc.,NEW CENTURY COMMUNCTN -CL A,6485B,D: Manufacturing,27 Printing Publishing And Allied Industries,Not tort,12/23/1991,confirmed,no 363 sale,31.0,DE / NY,OH ND,Cleveland,Filed at headquarters,debtors,prepackaged,1260.0,Company emerged,emerged 5 years did not refile,OH,Midwest,Cleveland,01/23/1992,c $500 million but less than $1billion,c 1 000 but less than 10 000,3.635045e+08,520,Chapter 11,Squire Sanders
1,Golden Books Family Entertainment Inc.,GOLDEN BOOKS FAMILY ENTMT,GBKF,D: Manufacturing,27 Printing Publishing And Allied Industries,Not tort,02/26/1999,confirmed,no 363 sale,210.0,DE,NY SD,New York,Filed at headquarters,debtors,prenegotiated,950.0,Company emerged,emerged 5 years refiled,NY,Northeast,New York,09/24/1999,d Less than $500 million,d 200 but less than 1 000,2.890201e+08,379,Chapter 11,Proskauer Rose
2,Readers Digest Association Inc.,READERS DIGEST ASSN INC,0090A,D: Manufacturing,27 Printing Publishing And Allied Industries,Not tort,08/24/2009,confirmed,no 363 sale,148.0,DE,NY SD,New York,Forum Shop,debtors,prenegotiated,4700.0,Company emerged,not emerged 5 years,NY,Northeast,White Plains,01/19/2010,b $1 billion but less than $10 billion,c 1 000 but less than 10 000,2.170307e+09,4497,Chapter 11,Kirkland Ellis
3,Idearc Inc.,SUPERMEDIA INC,SPMD,D: Manufacturing,27 Printing Publishing And Allied Industries,Not tort,03/31/2009,confirmed,no 363 sale,266.0,DE,TX ND,Dallas,Filed at headquarters,debtors,prenegotiated,6100.0,Company emerged,emerged 5 years refiled,TX,Southwest,Dallas,12/22/2009,b $1 billion but less than $10 billion,c 1 000 but less than 10 000,3.421480e+09,2089,Chapter 11,Fulbright Jaworski
4,Bush Industries Inc.,BUSH INDUSTRIES -CL A,BINDQ.1,D: Manufacturing,25 Furniture And Fixtures,Not tort,03/31/2004,confirmed,no 363 sale,212.0,DE,NY WD,Buffalo,Filed at headquarters,debtors,prenegotiated,3050.0,Company emerged,emerged 5 years did not refile,NY,Northeast,Buffalo,10/29/2004,d Less than $500 million,c 1 000 but less than 10 000,4.441155e+08,405,Chapter 11,Hodgson Russ

bank_dp = pd.read_excel(gp+"/ucla.xlsx")

bank_dp.head()

## New Bought Data

bank_dp = bank_dp.drop_duplicates("Ticker",keep="first")

bank_dp  = bank_dp[~bank_dp["Ticker"].isnull()]

cusip_y

rat_fin_1.shape

rat_fin_1[rat_fin_1["cusip_x"]=="770706109"]

In [34]:
from datetime import datetime
from dateutil.parser import parse

## More refinement necessary to get the reight merge

mergy = pd.merge(rat_fin_1, bank_dp, left_on="tic", right_on="Ticker", how="left")

mergy['public_date'] = mergy['public_date'].apply(lambda x: parse(str(x)))

mergy['Date Filed']= pd.to_datetime(mergy['Date Filed'])

mergy = mergy[mergy['public_date']<mergy['Date Filed']]

mergy_2 = mergy.groupby(["tic"]).tail(3) # This is 4 in the old vers

len(mergy_2["gvkey"].unique())

def replace_first_x(group_df, x, value):
    group_df.iloc[:, :] = 1
    group_df.iloc[-x:, :] = value
    return group_df


mergy_2["Target"] = 1

mergy_2["Target"] = mergy_2[["Target","tic"]].groupby(["tic"]).apply(lambda mergy_2: replace_first_x(mergy_2, 2, 0))

In [35]:
### Reasonable Merge - Paul: Instead of merging and obtaining new data for practice model multiply by two

dropsy = mergy_2["tic"].value_counts() >2

blom = np.where(dropsy==True)

dropsy = dropsy[:blom[0][-1]]

mergy_2 = mergy_2[mergy_2["tic"].isin(list(dropsy.index))]

print(len(mergy_2["tic"].unique()))

mergy_2 = mergy_2.reset_index(drop=True)

619

In [37]:
#Multiply by ratio, divide by year, divide by hoe many tickers in year

blok = {}

"""
blok[0] = mergy_2[mergy_2['public_date']<"1986-01-01"].shape[0]*10/4
blok[1] = (mergy_2[mergy_2['public_date']<"1996-01-01"].shape[0]-mergy_2[mergy_2['public_date']<"1986-01-01"].shape[0])*10/4
blok[2] = (mergy_2[mergy_2['public_date']<"2006-01-01"].shape[0]-mergy_2[mergy_2['public_date']<"1996-01-01"].shape[0])*10/4
blok[3] = (mergy_2[mergy_2['public_date']<"2016-01-01"].shape[0]-mergy_2[mergy_2['public_date']<"2006-01-01"].shape[0])*10/4

"""

"""
blok[0] = 4500
blok[1] = 5700
blok[2] = 5700
blok[3] = 3700
"""

blok = {}

blok[0] = mergy_2[mergy_2['public_date']<"1986-01-01"].shape[0]*25/4
blok[1] = (mergy_2[mergy_2['public_date']<"1996-01-01"].shape[0]-mergy_2[mergy_2['public_date']<"1986-01-01"].shape[0])*25/4
blok[2] = (mergy_2[mergy_2['public_date']<"2006-01-01"].shape[0]-mergy_2[mergy_2['public_date']<"1996-01-01"].shape[0])*20/4
blok[3] = (mergy_2[mergy_2['public_date']<"2016-01-01"].shape[0]-mergy_2[mergy_2['public_date']<"2006-01-01"].shape[0])*20/4


# Creating Stratefied DataFrame For Control Firms 

import random
random.seed(42)
conn = pd.DataFrame()
r = -1

for fixer, fixed, ratio in zip(["fixer_1976.csv","fixer_1986.csv","fixer_1996.csv","fixer_2006.csv"],
                               ["fixed_1976.csv","fixed_1986.csv","fixed_1996.csv","fixed_2006.csv"], 
                              ["ratio_1976.csv","ratio_1986.csv","ratio_1996.csv","ratio_2006.csv"]):

    r = r + 1
    
    fsmall = pd.read_csv(gp+"/Fixer/"+fixer)

    fbig = pd.read_csv(gp+"/Fixed/"+fixed)

    fcon = pd.merge(fsmall, fbig, on=["tic","datadate"], how="left")

    frat = pd.read_csv(gp+"/Ratio/"+ratio)
    

    rat_fin = pd.merge(frat, fcon, left_on=["public_date","gvkey"], right_on=["datadate","gvkey_x"], how="left")

    len(rat_fin["gvkey_x"].unique())

    rat_fin_1 = rat_fin[~rat_fin["gvkey_x"].isnull()]
    
    first = rat_fin_1

    first = first[~first["tic"].isin(list(mergy["tic"]))]
    
    first = first.sort_values(["tic","public_date"])

    first = first.groupby(["tic"]).tail(4)

    dropsy = first["tic"].value_counts() >3

    blom = np.where(dropsy==True)

    dropsy = dropsy[:blom[0][-1]]

    first = first[first["tic"].isin(list(dropsy.index))]

    first = first.reset_index(drop=True)
    first.shape

    name= list(first["tic"].unique())
    print(len(name))

    num_to_select = int(blok[r])       # set the number to select here.
    list_of = random.sample(name, num_to_select)

    first = first[first["tic"].isin(list_of)]
    print(first.shape)

    conn = conn.append(first)

4564
(3472, 174)
5833
(8524, 174)
5921
(16580, 174)
3988
(10960, 174)

In [38]:

# Full Merge and Edit

print(conn.shape)

conn = conn.reset_index(drop=True)

conn_1 = pd.merge(conn,bank_dp, left_on=["tic"], right_on=["Ticker"], how="left")

conn_1["Target"] = 1

connect = pd.concat((conn_1, mergy_2), axis=0)

connect.shape

connect = connect.drop(bank_dp.columns,axis=1)

connect = connect.reset_index(drop=True)
print(connect.shape)

saved = connect[["adate","Target","conm_x","consol","conm_y","costat","curcd","cusip_x","cusip_y","gvkey","gvkey_x","gvkey_y","datadate","indfmt","datafmt","tic","state","public_date","qdate","divyield"]]

connect = connect.drop(["adate","popsrc","conm_x","consol","conm_y","costat","curcd","cusip_x","cusip_y","gvkey","gvkey_x","gvkey_y","tic","datadate","indfmt","datafmt","state","public_date","qdate","divyield"],axis=1)

(39536, 174)
(41393, 175)

In [40]:

# Imputation

from fancyimpute import KNN

# df is my data frame with the missings. I keep only floats
df_numeric = connect.select_dtypes(include=[np.float]).as_matrix()

# I now run fancyimpute KNN, 
# it returns a np.array which I store as a pandas dataframe
df_filled_1 = pd.DataFrame(KNN(6).complete(df_numeric))

df_filled_1.columns = connect.select_dtypes(include=[np.float]).columns
df_filled_1.index = connect.select_dtypes(include=[np.float]).index
connect = df_filled_1.copy()

connect_2 = df_filled_1.pct_change().copy()

cols = []

for i in df_filled_1.columns:
    cols.append(i+'_prtc')

connect_2 = connect_2.replace("-inf",np.nan)
connect_2 = connect_2.replace("inf",np.nan)
connect_2.columns = cols

# df is my data frame with the missings. I keep only floats

df_numeric = connect_2.select_dtypes(include=[np.float]).as_matrix()
df_filled = pd.DataFrame(KNN(3).complete(df_numeric))
df_filled.columns = connect_2.select_dtypes(include=[np.float]).columns
df_filled.index = connect_2.select_dtypes(include=[np.float]).index
connect_2 = df_filled.copy()

Using TensorFlow backend.

Imputing row 1/41393 with 95 missing, elapsed time: 6221.435
Imputing row 101/41393 with 32 missing, elapsed time: 6222.935
Imputing row 201/41393 with 94 missing, elapsed time: 6223.685
Imputing row 301/41393 with 31 missing, elapsed time: 6224.498
Imputing row 401/41393 with 32 missing, elapsed time: 6225.232
Imputing row 501/41393 with 30 missing, elapsed time: 6226.670
Imputing row 601/41393 with 24 missing, elapsed time: 6227.513
Imputing row 701/41393 with 31 missing, elapsed time: 6228.341
Imputing row 801/41393 with 23 missing, elapsed time: 6229.185
Imputing row 901/41393 with 30 missing, elapsed time: 6230.560
Imputing row 1001/41393 with 43 missing, elapsed time: 6232.281
Imputing row 1101/41393 with 92 missing, elapsed time: 6233.484
Imputing row 1201/41393 with 30 missing, elapsed time: 6234.297
Imputing row 1301/41393 with 30 missing, elapsed time: 6235.625
Imputing row 1401/41393 with 30 missing, elapsed time: 6237.609
Imputing row 1501/41393 with 22 missing, elapsed time: 6238.500
Imputing row 1601/41393 with 23 missing, elapsed time: 6239.890
Imputing row 1701/41393 with 24 missing, elapsed time: 6240.578
Imputing row 1801/41393 with 28 missing, elapsed time: 6241.390
Imputing row 1901/41393 with 32 missing, elapsed time: 6242.125
Imputing row 2001/41393 with 39 missing, elapsed time: 6242.937
Imputing row 2101/41393 with 33 missing, elapsed time: 6243.640
Imputing row 2201/41393 with 32 missing, elapsed time: 6245.234
Imputing row 2301/41393 with 34 missing, elapsed time: 6245.923
Imputing row 2401/41393 with 23 missing, elapsed time: 6246.923
Imputing row 2501/41393 with 29 missing, elapsed time: 6247.689
Imputing row 2601/41393 with 23 missing, elapsed time: 6248.423
Imputing row 2701/41393 with 36 missing, elapsed time: 6249.345
Imputing row 2801/41393 with 47 missing, elapsed time: 6250.876
Imputing row 2901/41393 with 28 missing, elapsed time: 6251.611
Imputing row 3001/41393 with 149 missing, elapsed time: 6252.548
Imputing row 3101/41393 with 37 missing, elapsed time: 6253.533
Imputing row 3201/41393 with 27 missing, elapsed time: 6254.283
Imputing row 3301/41393 with 30 missing, elapsed time: 6255.470
Imputing row 3401/41393 with 30 missing, elapsed time: 6256.144
Imputing row 3501/41393 with 22 missing, elapsed time: 6256.816
Imputing row 3601/41393 with 22 missing, elapsed time: 6257.410
Imputing row 3701/41393 with 41 missing, elapsed time: 6258.050
Imputing row 3801/41393 with 18 missing, elapsed time: 6258.644
Imputing row 3901/41393 with 30 missing, elapsed time: 6259.316
Imputing row 4001/41393 with 25 missing, elapsed time: 6259.957
Imputing row 4101/41393 with 22 missing, elapsed time: 6260.675
Imputing row 4201/41393 with 17 missing, elapsed time: 6261.269
Imputing row 4301/41393 with 24 missing, elapsed time: 6261.925
Imputing row 4401/41393 with 12 missing, elapsed time: 6262.504
Imputing row 4501/41393 with 18 missing, elapsed time: 6263.050
Imputing row 4601/41393 with 148 missing, elapsed time: 6263.504
Imputing row 4701/41393 with 16 missing, elapsed time: 6264.222
Imputing row 4801/41393 with 15 missing, elapsed time: 6264.675
Imputing row 4901/41393 with 17 missing, elapsed time: 6265.269
Imputing row 5001/41393 with 14 missing, elapsed time: 6265.943
Imputing row 5101/41393 with 67 missing, elapsed time: 6266.787
Imputing row 5201/41393 with 69 missing, elapsed time: 6267.537
Imputing row 5301/41393 with 18 missing, elapsed time: 6268.146
Imputing row 5401/41393 with 66 missing, elapsed time: 6268.849
Imputing row 5501/41393 with 35 missing, elapsed time: 6269.615
Imputing row 5601/41393 with 14 missing, elapsed time: 6270.396
Imputing row 5701/41393 with 20 missing, elapsed time: 6271.052
Imputing row 5801/41393 with 148 missing, elapsed time: 6271.615
Imputing row 5901/41393 with 23 missing, elapsed time: 6272.287
Imputing row 6001/41393 with 12 missing, elapsed time: 6273.224
Imputing row 6101/41393 with 13 missing, elapsed time: 6273.849
Imputing row 6201/41393 with 26 missing, elapsed time: 6274.365
Imputing row 6301/41393 with 13 missing, elapsed time: 6275.256
Imputing row 6401/41393 with 16 missing, elapsed time: 6275.757
Imputing row 6501/41393 with 11 missing, elapsed time: 6276.351
Imputing row 6601/41393 with 67 missing, elapsed time: 6276.882
Imputing row 6701/41393 with 40 missing, elapsed time: 6277.398
Imputing row 6801/41393 with 66 missing, elapsed time: 6278.929
Imputing row 6901/41393 with 63 missing, elapsed time: 6280.257
Imputing row 7001/41393 with 34 missing, elapsed time: 6281.242
Imputing row 7101/41393 with 79 missing, elapsed time: 6282.148
Imputing row 7201/41393 with 16 missing, elapsed time: 6283.132
Imputing row 7301/41393 with 17 missing, elapsed time: 6283.617
Imputing row 7401/41393 with 149 missing, elapsed time: 6284.367
Imputing row 7501/41393 with 14 missing, elapsed time: 6285.117
Imputing row 7601/41393 with 65 missing, elapsed time: 6285.773
Imputing row 7701/41393 with 27 missing, elapsed time: 6286.382
Imputing row 7801/41393 with 18 missing, elapsed time: 6287.726
Imputing row 7901/41393 with 23 missing, elapsed time: 6288.773
Imputing row 8001/41393 with 112 missing, elapsed time: 6289.320
Imputing row 8101/41393 with 19 missing, elapsed time: 6289.976
Imputing row 8201/41393 with 66 missing, elapsed time: 6290.726
Imputing row 8301/41393 with 20 missing, elapsed time: 6291.306
Imputing row 8401/41393 with 112 missing, elapsed time: 6291.837
Imputing row 8501/41393 with 17 missing, elapsed time: 6292.603
Imputing row 8601/41393 with 35 missing, elapsed time: 6293.322
Imputing row 8701/41393 with 12 missing, elapsed time: 6294.619
Imputing row 8801/41393 with 64 missing, elapsed time: 6295.853
Imputing row 8901/41393 with 14 missing, elapsed time: 6296.541
Imputing row 9001/41393 with 14 missing, elapsed time: 6297.134
Imputing row 9101/41393 with 13 missing, elapsed time: 6297.806
Imputing row 9201/41393 with 22 missing, elapsed time: 6298.525
Imputing row 9301/41393 with 13 missing, elapsed time: 6299.166
Imputing row 9401/41393 with 14 missing, elapsed time: 6300.150
Imputing row 9501/41393 with 30 missing, elapsed time: 6300.884
Imputing row 9601/41393 with 63 missing, elapsed time: 6302.244
Imputing row 9701/41393 with 20 missing, elapsed time: 6302.931
Imputing row 9801/41393 with 18 missing, elapsed time: 6303.556
Imputing row 9901/41393 with 65 missing, elapsed time: 6304.103
Imputing row 10001/41393 with 17 missing, elapsed time: 6304.900
Imputing row 10101/41393 with 24 missing, elapsed time: 6305.463
Imputing row 10201/41393 with 11 missing, elapsed time: 6306.150
Imputing row 10301/41393 with 64 missing, elapsed time: 6307.447
Imputing row 10401/41393 with 14 missing, elapsed time: 6308.634
Imputing row 10501/41393 with 19 missing, elapsed time: 6310.228
Imputing row 10601/41393 with 15 missing, elapsed time: 6310.793
Imputing row 10701/41393 with 13 missing, elapsed time: 6311.340
Imputing row 10801/41393 with 21 missing, elapsed time: 6311.902
Imputing row 10901/41393 with 15 missing, elapsed time: 6312.715
Imputing row 11001/41393 with 19 missing, elapsed time: 6313.637
Imputing row 11101/41393 with 23 missing, elapsed time: 6314.699
Imputing row 11201/41393 with 17 missing, elapsed time: 6315.152
Imputing row 11301/41393 with 23 missing, elapsed time: 6315.746
Imputing row 11401/41393 with 84 missing, elapsed time: 6317.840
Imputing row 11501/41393 with 148 missing, elapsed time: 6318.652
Imputing row 11601/41393 with 16 missing, elapsed time: 6319.262
Imputing row 11701/41393 with 63 missing, elapsed time: 6319.730
Imputing row 11801/41393 with 10 missing, elapsed time: 6320.324
Imputing row 11901/41393 with 41 missing, elapsed time: 6321.027
Imputing row 12001/41393 with 8 missing, elapsed time: 6321.558
Imputing row 12101/41393 with 16 missing, elapsed time: 6321.871
Imputing row 12201/41393 with 22 missing, elapsed time: 6322.402
Imputing row 12301/41393 with 19 missing, elapsed time: 6323.043
Imputing row 12401/41393 with 25 missing, elapsed time: 6323.496
Imputing row 12501/41393 with 16 missing, elapsed time: 6324.012
Imputing row 12601/41393 with 24 missing, elapsed time: 6324.527
Imputing row 12701/41393 with 7 missing, elapsed time: 6325.512

Imputing row 12801/41393 with 11 missing, elapsed time: 6326.090
Imputing row 12901/41393 with 9 missing, elapsed time: 6326.496
Imputing row 13001/41393 with 23 missing, elapsed time: 6327.012
Imputing row 13101/41393 with 26 missing, elapsed time: 6327.449
Imputing row 13201/41393 with 9 missing, elapsed time: 6327.965
Imputing row 13301/41393 with 17 missing, elapsed time: 6328.418
Imputing row 13401/41393 with 33 missing, elapsed time: 6329.027
Imputing row 13501/41393 with 8 missing, elapsed time: 6329.465
Imputing row 13601/41393 with 6 missing, elapsed time: 6329.949
Imputing row 13701/41393 with 14 missing, elapsed time: 6330.355
Imputing row 13801/41393 with 20 missing, elapsed time: 6330.730
Imputing row 13901/41393 with 9 missing, elapsed time: 6331.152
Imputing row 14001/41393 with 32 missing, elapsed time: 6331.574
Imputing row 14101/41393 with 13 missing, elapsed time: 6332.215
Imputing row 14201/41393 with 61 missing, elapsed time: 6332.590
Imputing row 14301/41393 with 35 missing, elapsed time: 6333.652
Imputing row 14401/41393 with 13 missing, elapsed time: 6334.277
Imputing row 14501/41393 with 13 missing, elapsed time: 6334.856
Imputing row 14601/41393 with 33 missing, elapsed time: 6335.402
Imputing row 14701/41393 with 18 missing, elapsed time: 6336.109
Imputing row 14801/41393 with 17 missing, elapsed time: 6336.656
Imputing row 14901/41393 with 20 missing, elapsed time: 6337.172
Imputing row 15001/41393 with 5 missing, elapsed time: 6337.938
Imputing row 15101/41393 with 19 missing, elapsed time: 6338.531
Imputing row 15201/41393 with 24 missing, elapsed time: 6339.234
Imputing row 15301/41393 with 63 missing, elapsed time: 6340.000
Imputing row 15401/41393 with 7 missing, elapsed time: 6340.484
Imputing row 15501/41393 with 11 missing, elapsed time: 6341.063
Imputing row 15601/41393 with 9 missing, elapsed time: 6341.454
Imputing row 15701/41393 with 63 missing, elapsed time: 6341.969
Imputing row 15801/41393 with 10 missing, elapsed time: 6342.500
Imputing row 15901/41393 with 19 missing, elapsed time: 6342.969
Imputing row 16001/41393 with 22 missing, elapsed time: 6343.391
Imputing row 16101/41393 with 18 missing, elapsed time: 6343.906
Imputing row 16201/41393 with 15 missing, elapsed time: 6344.344
Imputing row 16301/41393 with 16 missing, elapsed time: 6344.875
Imputing row 16401/41393 with 11 missing, elapsed time: 6345.266
Imputing row 16501/41393 with 7 missing, elapsed time: 6345.688
Imputing row 16601/41393 with 26 missing, elapsed time: 6346.110
Imputing row 16701/41393 with 9 missing, elapsed time: 6346.469
Imputing row 16801/41393 with 20 missing, elapsed time: 6346.906
Imputing row 16901/41393 with 11 missing, elapsed time: 6347.281
Imputing row 17001/41393 with 5 missing, elapsed time: 6347.641
Imputing row 17101/41393 with 21 missing, elapsed time: 6348.125
Imputing row 17201/41393 with 12 missing, elapsed time: 6348.625
Imputing row 17301/41393 with 9 missing, elapsed time: 6349.031
Imputing row 17401/41393 with 18 missing, elapsed time: 6349.453
Imputing row 17501/41393 with 25 missing, elapsed time: 6350.110
Imputing row 17601/41393 with 12 missing, elapsed time: 6350.532
Imputing row 17701/41393 with 21 missing, elapsed time: 6351.016
Imputing row 17801/41393 with 13 missing, elapsed time: 6352.453
Imputing row 17901/41393 with 27 missing, elapsed time: 6353.125
Imputing row 18001/41393 with 11 missing, elapsed time: 6353.860
Imputing row 18101/41393 with 21 missing, elapsed time: 6354.453
Imputing row 18201/41393 with 23 missing, elapsed time: 6355.094
Imputing row 18301/41393 with 63 missing, elapsed time: 6355.735
Imputing row 18401/41393 with 16 missing, elapsed time: 6356.534
Imputing row 18501/41393 with 10 missing, elapsed time: 6357.127
Imputing row 18601/41393 with 16 missing, elapsed time: 6357.971
Imputing row 18701/41393 with 13 missing, elapsed time: 6358.455
Imputing row 18801/41393 with 24 missing, elapsed time: 6358.909
Imputing row 18901/41393 with 68 missing, elapsed time: 6359.455
Imputing row 19001/41393 with 34 missing, elapsed time: 6360.424
Imputing row 19101/41393 with 18 missing, elapsed time: 6360.971
Imputing row 19201/41393 with 7 missing, elapsed time: 6361.502
Imputing row 19301/41393 with 11 missing, elapsed time: 6362.002
Imputing row 19401/41393 with 30 missing, elapsed time: 6362.831
Imputing row 19501/41393 with 10 missing, elapsed time: 6363.518
Imputing row 19601/41393 with 16 missing, elapsed time: 6364.081
Imputing row 19701/41393 with 7 missing, elapsed time: 6364.518
Imputing row 19801/41393 with 23 missing, elapsed time: 6364.940
Imputing row 19901/41393 with 19 missing, elapsed time: 6365.502
Imputing row 20001/41393 with 19 missing, elapsed time: 6366.237
Imputing row 20101/41393 with 9 missing, elapsed time: 6366.752
Imputing row 20201/41393 with 18 missing, elapsed time: 6367.143
Imputing row 20301/41393 with 31 missing, elapsed time: 6367.737
Imputing row 20401/41393 with 9 missing, elapsed time: 6368.956
Imputing row 20501/41393 with 8 missing, elapsed time: 6369.315
Imputing row 20601/41393 with 17 missing, elapsed time: 6369.737
Imputing row 20701/41393 with 16 missing, elapsed time: 6370.706
Imputing row 20801/41393 with 59 missing, elapsed time: 6371.614
Imputing row 20901/41393 with 16 missing, elapsed time: 6372.114
Imputing row 21001/41393 with 11 missing, elapsed time: 6372.567
Imputing row 21101/41393 with 14 missing, elapsed time: 6372.989
Imputing row 21201/41393 with 17 missing, elapsed time: 6373.973
Imputing row 21301/41393 with 35 missing, elapsed time: 6374.442
Imputing row 21401/41393 with 21 missing, elapsed time: 6375.036
Imputing row 21501/41393 with 15 missing, elapsed time: 6375.520
Imputing row 21601/41393 with 11 missing, elapsed time: 6376.145
Imputing row 21701/41393 with 15 missing, elapsed time: 6376.645
Imputing row 21801/41393 with 9 missing, elapsed time: 6377.052
Imputing row 21901/41393 with 20 missing, elapsed time: 6377.458
Imputing row 22001/41393 with 13 missing, elapsed time: 6378.083
Imputing row 22101/41393 with 18 missing, elapsed time: 6378.489
Imputing row 22201/41393 with 59 missing, elapsed time: 6378.927
Imputing row 22301/41393 with 34 missing, elapsed time: 6379.567
Imputing row 22401/41393 with 22 missing, elapsed time: 6380.083
Imputing row 22501/41393 with 61 missing, elapsed time: 6380.583
Imputing row 22601/41393 with 12 missing, elapsed time: 6381.083
Imputing row 22701/41393 with 22 missing, elapsed time: 6382.052
Imputing row 22801/41393 with 18 missing, elapsed time: 6382.911
Imputing row 22901/41393 with 13 missing, elapsed time: 6383.364
Imputing row 23001/41393 with 19 missing, elapsed time: 6384.036
Imputing row 23101/41393 with 22 missing, elapsed time: 6384.552
Imputing row 23201/41393 with 8 missing, elapsed time: 6385.145
Imputing row 23301/41393 with 19 missing, elapsed time: 6385.614
Imputing row 23401/41393 with 71 missing, elapsed time: 6386.270
Imputing row 23501/41393 with 68 missing, elapsed time: 6386.802
Imputing row 23601/41393 with 14 missing, elapsed time: 6387.255
Imputing row 23701/41393 with 17 missing, elapsed time: 6388.302
Imputing row 23801/41393 with 33 missing, elapsed time: 6388.724
Imputing row 23901/41393 with 60 missing, elapsed time: 6389.427
Imputing row 24001/41393 with 21 missing, elapsed time: 6389.942
Imputing row 24101/41393 with 19 missing, elapsed time: 6390.458
Imputing row 24201/41393 with 15 missing, elapsed time: 6390.974
Imputing row 24301/41393 with 20 missing, elapsed time: 6391.520
Imputing row 24401/41393 with 10 missing, elapsed time: 6391.911
Imputing row 24501/41393 with 10 missing, elapsed time: 6392.349
Imputing row 24601/41393 with 8 missing, elapsed time: 6393.161
Imputing row 24701/41393 with 15 missing, elapsed time: 6393.567
Imputing row 24801/41393 with 15 missing, elapsed time: 6393.958
Imputing row 24901/41393 with 18 missing, elapsed time: 6394.411
Imputing row 25001/41393 with 16 missing, elapsed time: 6394.849
Imputing row 25101/41393 with 33 missing, elapsed time: 6395.333
Imputing row 25201/41393 with 19 missing, elapsed time: 6395.896
Imputing row 25301/41393 with 16 missing, elapsed time: 6396.255
Imputing row 25401/41393 with 9 missing, elapsed time: 6396.771

Imputing row 25501/41393 with 13 missing, elapsed time: 6397.255
Imputing row 25601/41393 with 62 missing, elapsed time: 6397.677
Imputing row 25701/41393 with 9 missing, elapsed time: 6398.208
Imputing row 25801/41393 with 14 missing, elapsed time: 6398.677
Imputing row 25901/41393 with 17 missing, elapsed time: 6399.239
Imputing row 26001/41393 with 20 missing, elapsed time: 6399.677
Imputing row 26101/41393 with 27 missing, elapsed time: 6400.177
Imputing row 26201/41393 with 9 missing, elapsed time: 6400.677
Imputing row 26301/41393 with 18 missing, elapsed time: 6401.288
Imputing row 26401/41393 with 39 missing, elapsed time: 6401.788
Imputing row 26501/41393 with 10 missing, elapsed time: 6402.257
Imputing row 26601/41393 with 12 missing, elapsed time: 6402.694
Imputing row 26701/41393 with 33 missing, elapsed time: 6403.194
Imputing row 26801/41393 with 15 missing, elapsed time: 6403.585
Imputing row 26901/41393 with 8 missing, elapsed time: 6404.007
Imputing row 27001/41393 with 12 missing, elapsed time: 6404.491
Imputing row 27101/41393 with 7 missing, elapsed time: 6404.991
Imputing row 27201/41393 with 18 missing, elapsed time: 6405.523
Imputing row 27301/41393 with 17 missing, elapsed time: 6406.038
Imputing row 27401/41393 with 20 missing, elapsed time: 6406.710
Imputing row 27501/41393 with 39 missing, elapsed time: 6407.413
Imputing row 27601/41393 with 25 missing, elapsed time: 6408.070
Imputing row 27701/41393 with 13 missing, elapsed time: 6408.554
Imputing row 27801/41393 with 13 missing, elapsed time: 6409.007
Imputing row 27901/41393 with 34 missing, elapsed time: 6409.445
Imputing row 28001/41393 with 28 missing, elapsed time: 6409.976
Imputing row 28101/41393 with 13 missing, elapsed time: 6410.491
Imputing row 28201/41393 with 8 missing, elapsed time: 6410.882
Imputing row 28301/41393 with 31 missing, elapsed time: 6411.491
Imputing row 28401/41393 with 12 missing, elapsed time: 6411.976
Imputing row 28501/41393 with 13 missing, elapsed time: 6412.351
Imputing row 28601/41393 with 6 missing, elapsed time: 6412.757
Imputing row 28701/41393 with 34 missing, elapsed time: 6413.257
Imputing row 28801/41393 with 5 missing, elapsed time: 6413.632
Imputing row 28901/41393 with 20 missing, elapsed time: 6414.054
Imputing row 29001/41393 with 5 missing, elapsed time: 6414.398
Imputing row 29101/41393 with 7 missing, elapsed time: 6414.742
Imputing row 29201/41393 with 32 missing, elapsed time: 6415.210
Imputing row 29301/41393 with 17 missing, elapsed time: 6415.554
Imputing row 29401/41393 with 7 missing, elapsed time: 6415.913
Imputing row 29501/41393 with 11 missing, elapsed time: 6416.273
Imputing row 29601/41393 with 14 missing, elapsed time: 6416.585
Imputing row 29701/41393 with 30 missing, elapsed time: 6416.960
Imputing row 29801/41393 with 3 missing, elapsed time: 6417.398
Imputing row 29901/41393 with 13 missing, elapsed time: 6417.820
Imputing row 30001/41393 with 14 missing, elapsed time: 6418.273
Imputing row 30101/41393 with 12 missing, elapsed time: 6418.773
Imputing row 30201/41393 with 6 missing, elapsed time: 6419.492
Imputing row 30301/41393 with 15 missing, elapsed time: 6419.992
Imputing row 30401/41393 with 15 missing, elapsed time: 6420.445
Imputing row 30501/41393 with 12 missing, elapsed time: 6420.915
Imputing row 30601/41393 with 32 missing, elapsed time: 6421.275
Imputing row 30701/41393 with 13 missing, elapsed time: 6421.775
Imputing row 30801/41393 with 9 missing, elapsed time: 6422.243
Imputing row 30901/41393 with 13 missing, elapsed time: 6422.603
Imputing row 31001/41393 with 6 missing, elapsed time: 6422.931
Imputing row 31101/41393 with 17 missing, elapsed time: 6423.525
Imputing row 31201/41393 with 31 missing, elapsed time: 6423.931
Imputing row 31301/41393 with 9 missing, elapsed time: 6424.540
Imputing row 31401/41393 with 13 missing, elapsed time: 6425.212
Imputing row 31501/41393 with 6 missing, elapsed time: 6425.618
Imputing row 31601/41393 with 17 missing, elapsed time: 6425.978
Imputing row 31701/41393 with 16 missing, elapsed time: 6426.275
Imputing row 31801/41393 with 30 missing, elapsed time: 6426.665
Imputing row 31901/41393 with 13 missing, elapsed time: 6427.087
Imputing row 32001/41393 with 11 missing, elapsed time: 6427.525
Imputing row 32101/41393 with 11 missing, elapsed time: 6427.868
Imputing row 32201/41393 with 17 missing, elapsed time: 6428.275
Imputing row 32301/41393 with 7 missing, elapsed time: 6428.650
Imputing row 32401/41393 with 13 missing, elapsed time: 6429.337
Imputing row 32501/41393 with 33 missing, elapsed time: 6429.915
Imputing row 32601/41393 with 22 missing, elapsed time: 6430.384
Imputing row 32701/41393 with 9 missing, elapsed time: 6430.900
Imputing row 32801/41393 with 33 missing, elapsed time: 6431.368
Imputing row 32901/41393 with 22 missing, elapsed time: 6431.806
Imputing row 33001/41393 with 16 missing, elapsed time: 6432.165
Imputing row 33101/41393 with 18 missing, elapsed time: 6432.540
Imputing row 33201/41393 with 18 missing, elapsed time: 6432.978
Imputing row 33301/41393 with 32 missing, elapsed time: 6433.400
Imputing row 33401/41393 with 7 missing, elapsed time: 6433.822
Imputing row 33501/41393 with 4 missing, elapsed time: 6434.244
Imputing row 33601/41393 with 5 missing, elapsed time: 6434.603
Imputing row 33701/41393 with 7 missing, elapsed time: 6435.009
Imputing row 33801/41393 with 33 missing, elapsed time: 6435.447
Imputing row 33901/41393 with 4 missing, elapsed time: 6435.806
Imputing row 34001/41393 with 34 missing, elapsed time: 6436.167
Imputing row 34101/41393 with 25 missing, elapsed time: 6436.480
Imputing row 34201/41393 with 20 missing, elapsed time: 6436.792
Imputing row 34301/41393 with 31 missing, elapsed time: 6437.136
Imputing row 34401/41393 with 10 missing, elapsed time: 6437.480
Imputing row 34501/41393 with 34 missing, elapsed time: 6437.808
Imputing row 34601/41393 with 14 missing, elapsed time: 6438.199
Imputing row 34701/41393 with 11 missing, elapsed time: 6438.636
Imputing row 34801/41393 with 29 missing, elapsed time: 6438.995
Imputing row 34901/41393 with 18 missing, elapsed time: 6439.386
Imputing row 35001/41393 with 19 missing, elapsed time: 6439.855
Imputing row 35101/41393 with 10 missing, elapsed time: 6440.292
Imputing row 35201/41393 with 10 missing, elapsed time: 6440.636
Imputing row 35301/41393 with 24 missing, elapsed time: 6441.027
Imputing row 35401/41393 with 35 missing, elapsed time: 6441.308
Imputing row 35501/41393 with 7 missing, elapsed time: 6441.902
Imputing row 35601/41393 with 9 missing, elapsed time: 6442.277
Imputing row 35701/41393 with 16 missing, elapsed time: 6442.808
Imputing row 35801/41393 with 23 missing, elapsed time: 6443.230
Imputing row 35901/41393 with 23 missing, elapsed time: 6443.683
Imputing row 36001/41393 with 22 missing, elapsed time: 6444.152
Imputing row 36101/41393 with 17 missing, elapsed time: 6444.683
Imputing row 36201/41393 with 41 missing, elapsed time: 6445.058
Imputing row 36301/41393 with 18 missing, elapsed time: 6445.480
Imputing row 36401/41393 with 25 missing, elapsed time: 6445.949
Imputing row 36501/41393 with 19 missing, elapsed time: 6446.292
Imputing row 36601/41393 with 22 missing, elapsed time: 6446.746
Imputing row 36701/41393 with 11 missing, elapsed time: 6447.152
Imputing row 36801/41393 with 23 missing, elapsed time: 6447.777
Imputing row 36901/41393 with 9 missing, elapsed time: 6448.183
Imputing row 37001/41393 with 6 missing, elapsed time: 6448.574
Imputing row 37101/41393 with 33 missing, elapsed time: 6448.824
Imputing row 37201/41393 with 20 missing, elapsed time: 6449.277
Imputing row 37301/41393 with 7 missing, elapsed time: 6449.652
Imputing row 37401/41393 with 15 missing, elapsed time: 6450.355
Imputing row 37501/41393 with 12 missing, elapsed time: 6450.699
Imputing row 37601/41393 with 6 missing, elapsed time: 6451.089
Imputing row 37701/41393 with 14 missing, elapsed time: 6451.464
Imputing row 37801/41393 with 10 missing, elapsed time: 6451.839
Imputing row 37901/41393 with 31 missing, elapsed time: 6452.292
Imputing row 38001/41393 with 22 missing, elapsed time: 6452.683
Imputing row 38101/41393 with 17 missing, elapsed time: 6453.136

Imputing row 38201/41393 with 15 missing, elapsed time: 6453.574
Imputing row 38301/41393 with 14 missing, elapsed time: 6453.902
Imputing row 38401/41393 with 14 missing, elapsed time: 6454.324
Imputing row 38501/41393 with 9 missing, elapsed time: 6454.761
Imputing row 38601/41393 with 16 missing, elapsed time: 6455.027
Imputing row 38701/41393 with 9 missing, elapsed time: 6455.605
Imputing row 38801/41393 with 11 missing, elapsed time: 6456.029
Imputing row 38901/41393 with 15 missing, elapsed time: 6456.466
Imputing row 39001/41393 with 23 missing, elapsed time: 6456.826
Imputing row 39101/41393 with 6 missing, elapsed time: 6457.310
Imputing row 39201/41393 with 5 missing, elapsed time: 6457.732
Imputing row 39301/41393 with 6 missing, elapsed time: 6458.076
Imputing row 39401/41393 with 19 missing, elapsed time: 6458.482
Imputing row 39501/41393 with 22 missing, elapsed time: 6458.857
Imputing row 39601/41393 with 54 missing, elapsed time: 6459.357
Imputing row 39701/41393 with 13 missing, elapsed time: 6459.810
Imputing row 39801/41393 with 29 missing, elapsed time: 6460.373
Imputing row 39901/41393 with 13 missing, elapsed time: 6460.763
Imputing row 40001/41393 with 10 missing, elapsed time: 6461.232
Imputing row 40101/41393 with 26 missing, elapsed time: 6461.748
Imputing row 40201/41393 with 22 missing, elapsed time: 6462.216
Imputing row 40301/41393 with 14 missing, elapsed time: 6462.654
Imputing row 40401/41393 with 33 missing, elapsed time: 6463.013
Imputing row 40501/41393 with 12 missing, elapsed time: 6463.498
Imputing row 40601/41393 with 11 missing, elapsed time: 6464.263
Imputing row 40701/41393 with 11 missing, elapsed time: 6464.576
Imputing row 40801/41393 with 23 missing, elapsed time: 6464.935
Imputing row 40901/41393 with 17 missing, elapsed time: 6465.404
Imputing row 41001/41393 with 16 missing, elapsed time: 6465.810
Imputing row 41101/41393 with 8 missing, elapsed time: 6466.203
Imputing row 41201/41393 with 16 missing, elapsed time: 6466.640
Imputing row 41301/41393 with 23 missing, elapsed time: 6467.000
Imputing row 1/41393 with 154 missing, elapsed time: 3411.851
Imputing row 101/41393 with 8 missing, elapsed time: 3411.914
Imputing row 201/41393 with 17 missing, elapsed time: 3411.961
Imputing row 301/41393 with 12 missing, elapsed time: 3412.023
Imputing row 401/41393 with 10 missing, elapsed time: 3412.086
Imputing row 501/41393 with 8 missing, elapsed time: 3412.148
Imputing row 601/41393 with 5 missing, elapsed time: 3412.226
Imputing row 701/41393 with 12 missing, elapsed time: 3412.289
Imputing row 801/41393 with 5 missing, elapsed time: 3412.351
Imputing row 901/41393 with 6 missing, elapsed time: 3412.398
Imputing row 1001/41393 with 6 missing, elapsed time: 3412.461
Imputing row 1101/41393 with 8 missing, elapsed time: 3412.523
Imputing row 1201/41393 with 11 missing, elapsed time: 3412.586
Imputing row 1301/41393 with 5 missing, elapsed time: 3412.648
Imputing row 1401/41393 with 12 missing, elapsed time: 3412.711
Imputing row 1501/41393 with 10 missing, elapsed time: 3412.773
Imputing row 1601/41393 with 3 missing, elapsed time: 3412.851
Imputing row 1701/41393 with 4 missing, elapsed time: 3412.898
Imputing row 1801/41393 with 13 missing, elapsed time: 3412.961
Imputing row 1901/41393 with 9 missing, elapsed time: 3413.039
Imputing row 2001/41393 with 11 missing, elapsed time: 3413.101
Imputing row 2101/41393 with 12 missing, elapsed time: 3413.164
Imputing row 2201/41393 with 12 missing, elapsed time: 3413.242
Imputing row 2301/41393 with 10 missing, elapsed time: 3413.305
Imputing row 2401/41393 with 5 missing, elapsed time: 3413.367
Imputing row 2501/41393 with 7 missing, elapsed time: 3413.430
Imputing row 2601/41393 with 7 missing, elapsed time: 3413.476
Imputing row 2701/41393 with 9 missing, elapsed time: 3413.539
Imputing row 2801/41393 with 11 missing, elapsed time: 3413.617
Imputing row 2901/41393 with 11 missing, elapsed time: 3413.680
Imputing row 3001/41393 with 4 missing, elapsed time: 3413.742
Imputing row 3101/41393 with 9 missing, elapsed time: 3413.805
Imputing row 3201/41393 with 5 missing, elapsed time: 3413.867
Imputing row 3301/41393 with 7 missing, elapsed time: 3413.930
Imputing row 3401/41393 with 7 missing, elapsed time: 3413.992
Imputing row 3501/41393 with 10 missing, elapsed time: 3414.055
Imputing row 3601/41393 with 5 missing, elapsed time: 3414.117
Imputing row 3701/41393 with 16 missing, elapsed time: 3414.195
Imputing row 3801/41393 with 18 missing, elapsed time: 3414.273
Imputing row 3901/41393 with 16 missing, elapsed time: 3414.351
Imputing row 4001/41393 with 17 missing, elapsed time: 3414.414
Imputing row 4101/41393 with 4 missing, elapsed time: 3414.476
Imputing row 4201/41393 with 10 missing, elapsed time: 3414.555
Imputing row 4301/41393 with 13 missing, elapsed time: 3414.633
Imputing row 4401/41393 with 7 missing, elapsed time: 3414.711
Imputing row 4501/41393 with 5 missing, elapsed time: 3414.789
Imputing row 4601/41393 with 7 missing, elapsed time: 3414.867
Imputing row 4701/41393 with 17 missing, elapsed time: 3414.945
Imputing row 4801/41393 with 9 missing, elapsed time: 3415.023
Imputing row 4901/41393 with 7 missing, elapsed time: 3415.086
Imputing row 5001/41393 with 12 missing, elapsed time: 3415.148
Imputing row 5101/41393 with 9 missing, elapsed time: 3415.226
Imputing row 5201/41393 with 7 missing, elapsed time: 3415.305
Imputing row 5301/41393 with 13 missing, elapsed time: 3415.383
Imputing row 5401/41393 with 10 missing, elapsed time: 3415.461
Imputing row 5501/41393 with 17 missing, elapsed time: 3415.539
Imputing row 5601/41393 with 6 missing, elapsed time: 3415.633
Imputing row 5701/41393 with 5 missing, elapsed time: 3415.695
Imputing row 5801/41393 with 9 missing, elapsed time: 3415.773
Imputing row 5901/41393 with 17 missing, elapsed time: 3415.852
Imputing row 6001/41393 with 11 missing, elapsed time: 3415.945
Imputing row 6101/41393 with 11 missing, elapsed time: 3416.023
Imputing row 6201/41393 with 14 missing, elapsed time: 3416.102
Imputing row 6301/41393 with 9 missing, elapsed time: 3416.180
Imputing row 6401/41393 with 15 missing, elapsed time: 3416.242
Imputing row 6501/41393 with 6 missing, elapsed time: 3416.336
Imputing row 6601/41393 with 5 missing, elapsed time: 3416.398
Imputing row 6701/41393 with 7 missing, elapsed time: 3416.477
Imputing row 6801/41393 with 7 missing, elapsed time: 3416.555
Imputing row 6901/41393 with 7 missing, elapsed time: 3416.617
Imputing row 7001/41393 with 15 missing, elapsed time: 3416.695
Imputing row 7101/41393 with 4 missing, elapsed time: 3416.773
Imputing row 7201/41393 with 9 missing, elapsed time: 3416.836
Imputing row 7301/41393 with 18 missing, elapsed time: 3416.930
Imputing row 7401/41393 with 6 missing, elapsed time: 3416.992
Imputing row 7501/41393 with 17 missing, elapsed time: 3417.070
Imputing row 7601/41393 with 7 missing, elapsed time: 3417.133
Imputing row 7701/41393 with 17 missing, elapsed time: 3417.211
Imputing row 7801/41393 with 10 missing, elapsed time: 3417.273
Imputing row 7901/41393 with 15 missing, elapsed time: 3417.336
Imputing row 8001/41393 with 2 missing, elapsed time: 3417.414
Imputing row 8101/41393 with 17 missing, elapsed time: 3417.523
Imputing row 8201/41393 with 7 missing, elapsed time: 3417.602
Imputing row 8301/41393 with 7 missing, elapsed time: 3417.680
Imputing row 8401/41393 with 13 missing, elapsed time: 3417.758
Imputing row 8501/41393 with 8 missing, elapsed time: 3417.852
Imputing row 8601/41393 with 9 missing, elapsed time: 3417.914
Imputing row 8701/41393 with 7 missing, elapsed time: 3417.992
Imputing row 8801/41393 with 7 missing, elapsed time: 3418.070
Imputing row 8901/41393 with 14 missing, elapsed time: 3418.148
Imputing row 9001/41393 with 6 missing, elapsed time: 3418.195
Imputing row 9101/41393 with 13 missing, elapsed time: 3418.273
Imputing row 9201/41393 with 14 missing, elapsed time: 3418.336
Imputing row 9301/41393 with 7 missing, elapsed time: 3418.414
Imputing row 9401/41393 with 9 missing, elapsed time: 3418.477
Imputing row 9501/41393 with 2 missing, elapsed time: 3418.555
Imputing row 9601/41393 with 8 missing, elapsed time: 3418.617

Imputing row 9701/41393 with 6 missing, elapsed time: 3418.695
Imputing row 9801/41393 with 13 missing, elapsed time: 3418.773
Imputing row 9901/41393 with 8 missing, elapsed time: 3418.852
Imputing row 10001/41393 with 15 missing, elapsed time: 3418.930
Imputing row 10101/41393 with 5 missing, elapsed time: 3418.992
Imputing row 10201/41393 with 5 missing, elapsed time: 3419.070
Imputing row 10301/41393 with 7 missing, elapsed time: 3419.148
Imputing row 10401/41393 with 12 missing, elapsed time: 3419.242
Imputing row 10501/41393 with 16 missing, elapsed time: 3419.320
Imputing row 10601/41393 with 13 missing, elapsed time: 3419.414
Imputing row 10701/41393 with 13 missing, elapsed time: 3419.492
Imputing row 10801/41393 with 13 missing, elapsed time: 3419.555
Imputing row 10901/41393 with 8 missing, elapsed time: 3419.633
Imputing row 11001/41393 with 8 missing, elapsed time: 3419.695
Imputing row 11101/41393 with 10 missing, elapsed time: 3419.758
Imputing row 11201/41393 with 14 missing, elapsed time: 3419.820
Imputing row 11301/41393 with 10 missing, elapsed time: 3419.914
Imputing row 11401/41393 with 7 missing, elapsed time: 3419.977
Imputing row 11501/41393 with 5 missing, elapsed time: 3420.039
Imputing row 11601/41393 with 11 missing, elapsed time: 3420.102
Imputing row 11701/41393 with 6 missing, elapsed time: 3420.180
Imputing row 11801/41393 with 6 missing, elapsed time: 3420.242
Imputing row 11901/41393 with 5 missing, elapsed time: 3420.320
Imputing row 12001/41393 with 10 missing, elapsed time: 3420.398
Imputing row 12101/41393 with 5 missing, elapsed time: 3420.461
Imputing row 12201/41393 with 11 missing, elapsed time: 3420.539
Imputing row 12301/41393 with 8 missing, elapsed time: 3420.602
Imputing row 12401/41393 with 15 missing, elapsed time: 3420.664
Imputing row 12501/41393 with 5 missing, elapsed time: 3420.727
Imputing row 12601/41393 with 23 missing, elapsed time: 3420.805
Imputing row 12701/41393 with 6 missing, elapsed time: 3420.867
Imputing row 12801/41393 with 9 missing, elapsed time: 3420.961
Imputing row 12901/41393 with 12 missing, elapsed time: 3421.023
Imputing row 13001/41393 with 15 missing, elapsed time: 3421.086
Imputing row 13101/41393 with 12 missing, elapsed time: 3421.164
Imputing row 13201/41393 with 15 missing, elapsed time: 3421.227
Imputing row 13301/41393 with 10 missing, elapsed time: 3421.289
Imputing row 13401/41393 with 13 missing, elapsed time: 3421.369
Imputing row 13501/41393 with 10 missing, elapsed time: 3421.447
Imputing row 13601/41393 with 13 missing, elapsed time: 3421.525
Imputing row 13701/41393 with 12 missing, elapsed time: 3421.588
Imputing row 13801/41393 with 14 missing, elapsed time: 3421.650
Imputing row 13901/41393 with 8 missing, elapsed time: 3421.713
Imputing row 14001/41393 with 3 missing, elapsed time: 3421.853
Imputing row 14101/41393 with 17 missing, elapsed time: 3421.916
Imputing row 14201/41393 with 3 missing, elapsed time: 3421.978
Imputing row 14301/41393 with 2 missing, elapsed time: 3422.041
Imputing row 14401/41393 with 8 missing, elapsed time: 3422.119
Imputing row 14501/41393 with 13 missing, elapsed time: 3422.197
Imputing row 14601/41393 with 9 missing, elapsed time: 3422.275
Imputing row 14701/41393 with 18 missing, elapsed time: 3422.338
Imputing row 14801/41393 with 11 missing, elapsed time: 3422.416
Imputing row 14901/41393 with 5 missing, elapsed time: 3422.494
Imputing row 15001/41393 with 6 missing, elapsed time: 3422.572
Imputing row 15101/41393 with 17 missing, elapsed time: 3422.635
Imputing row 15201/41393 with 9 missing, elapsed time: 3422.697
Imputing row 15301/41393 with 12 missing, elapsed time: 3422.775
Imputing row 15401/41393 with 3 missing, elapsed time: 3422.838
Imputing row 15501/41393 with 8 missing, elapsed time: 3422.900
Imputing row 15601/41393 with 6 missing, elapsed time: 3422.978
Imputing row 15701/41393 with 7 missing, elapsed time: 3423.057
Imputing row 15801/41393 with 10 missing, elapsed time: 3423.135
Imputing row 15901/41393 with 8 missing, elapsed time: 3423.197
Imputing row 16001/41393 with 12 missing, elapsed time: 3423.275
Imputing row 16101/41393 with 16 missing, elapsed time: 3423.353
Imputing row 16201/41393 with 7 missing, elapsed time: 3423.416
Imputing row 16301/41393 with 22 missing, elapsed time: 3423.494
Imputing row 16401/41393 with 3 missing, elapsed time: 3423.572
Imputing row 16501/41393 with 6 missing, elapsed time: 3423.650
Imputing row 16601/41393 with 7 missing, elapsed time: 3423.713
Imputing row 16701/41393 with 7 missing, elapsed time: 3423.775
Imputing row 16801/41393 with 20 missing, elapsed time: 3423.854
Imputing row 16901/41393 with 4 missing, elapsed time: 3423.932
Imputing row 17001/41393 with 7 missing, elapsed time: 3423.994
Imputing row 17101/41393 with 26 missing, elapsed time: 3424.072
Imputing row 17201/41393 with 19 missing, elapsed time: 3424.150
Imputing row 17301/41393 with 10 missing, elapsed time: 3424.228
Imputing row 17401/41393 with 10 missing, elapsed time: 3424.291
Imputing row 17501/41393 with 4 missing, elapsed time: 3424.385
Imputing row 17601/41393 with 17 missing, elapsed time: 3424.447
Imputing row 17701/41393 with 12 missing, elapsed time: 3424.525
Imputing row 17801/41393 with 8 missing, elapsed time: 3424.604
Imputing row 17901/41393 with 16 missing, elapsed time: 3424.666
Imputing row 18001/41393 with 13 missing, elapsed time: 3424.744
Imputing row 18101/41393 with 11 missing, elapsed time: 3424.807
Imputing row 18201/41393 with 6 missing, elapsed time: 3424.885
Imputing row 18301/41393 with 9 missing, elapsed time: 3424.963
Imputing row 18401/41393 with 12 missing, elapsed time: 3425.025
Imputing row 18501/41393 with 8 missing, elapsed time: 3425.088
Imputing row 18601/41393 with 17 missing, elapsed time: 3425.166
Imputing row 18701/41393 with 12 missing, elapsed time: 3425.244
Imputing row 18801/41393 with 11 missing, elapsed time: 3425.307
Imputing row 18901/41393 with 11 missing, elapsed time: 3425.354
Imputing row 19001/41393 with 8 missing, elapsed time: 3425.432
Imputing row 19101/41393 with 14 missing, elapsed time: 3425.494
Imputing row 19201/41393 with 6 missing, elapsed time: 3425.572
Imputing row 19301/41393 with 3 missing, elapsed time: 3425.650
Imputing row 19401/41393 with 12 missing, elapsed time: 3425.713
Imputing row 19501/41393 with 12 missing, elapsed time: 3425.775
Imputing row 19601/41393 with 7 missing, elapsed time: 3425.838
Imputing row 19701/41393 with 2 missing, elapsed time: 3425.916
Imputing row 19801/41393 with 17 missing, elapsed time: 3425.994
Imputing row 19901/41393 with 14 missing, elapsed time: 3426.057
Imputing row 20001/41393 with 7 missing, elapsed time: 3426.150
Imputing row 20101/41393 with 8 missing, elapsed time: 3426.229
Imputing row 20201/41393 with 14 missing, elapsed time: 3426.322
Imputing row 20301/41393 with 10 missing, elapsed time: 3426.385
Imputing row 20401/41393 with 3 missing, elapsed time: 3426.463
Imputing row 20501/41393 with 4 missing, elapsed time: 3426.541
Imputing row 20601/41393 with 10 missing, elapsed time: 3426.619
Imputing row 20701/41393 with 8 missing, elapsed time: 3426.682
Imputing row 20801/41393 with 10 missing, elapsed time: 3426.760
Imputing row 20901/41393 with 17 missing, elapsed time: 3426.838
Imputing row 21001/41393 with 12 missing, elapsed time: 3426.916
Imputing row 21101/41393 with 10 missing, elapsed time: 3426.994
Imputing row 21201/41393 with 16 missing, elapsed time: 3427.057
Imputing row 21301/41393 with 5 missing, elapsed time: 3427.119
Imputing row 21401/41393 with 11 missing, elapsed time: 3427.182
Imputing row 21501/41393 with 8 missing, elapsed time: 3427.260
Imputing row 21601/41393 with 4 missing, elapsed time: 3427.322
Imputing row 21701/41393 with 11 missing, elapsed time: 3427.400
Imputing row 21801/41393 with 8 missing, elapsed time: 3427.463
Imputing row 21901/41393 with 17 missing, elapsed time: 3427.541
Imputing row 22001/41393 with 14 missing, elapsed time: 3427.604
Imputing row 22101/41393 with 8 missing, elapsed time: 3427.666
Imputing row 22201/41393 with 8 missing, elapsed time: 3427.744
Imputing row 22301/41393 with 6 missing, elapsed time: 3427.807
Imputing row 22401/41393 with 17 missing, elapsed time: 3427.869
Imputing row 22501/41393 with 9 missing, elapsed time: 3427.963
Imputing row 22601/41393 with 13 missing, elapsed time: 3428.025

Imputing row 22701/41393 with 29 missing, elapsed time: 3428.088
Imputing row 22801/41393 with 10 missing, elapsed time: 3428.150
Imputing row 22901/41393 with 12 missing, elapsed time: 3428.213
Imputing row 23001/41393 with 11 missing, elapsed time: 3428.276
Imputing row 23101/41393 with 10 missing, elapsed time: 3428.338
Imputing row 23201/41393 with 18 missing, elapsed time: 3428.416
Imputing row 23301/41393 with 11 missing, elapsed time: 3428.479
Imputing row 23401/41393 with 9 missing, elapsed time: 3428.541
Imputing row 23501/41393 with 8 missing, elapsed time: 3428.604
Imputing row 23601/41393 with 1 missing, elapsed time: 3428.666
Imputing row 23701/41393 with 9 missing, elapsed time: 3428.760
Imputing row 23801/41393 with 5 missing, elapsed time: 3428.822
Imputing row 23901/41393 with 8 missing, elapsed time: 3428.916
Imputing row 24001/41393 with 9 missing, elapsed time: 3428.979
Imputing row 24101/41393 with 15 missing, elapsed time: 3429.057
Imputing row 24201/41393 with 13 missing, elapsed time: 3429.119
Imputing row 24301/41393 with 14 missing, elapsed time: 3429.197
Imputing row 24401/41393 with 8 missing, elapsed time: 3429.291
Imputing row 24501/41393 with 5 missing, elapsed time: 3429.369
Imputing row 24601/41393 with 10 missing, elapsed time: 3429.447
Imputing row 24701/41393 with 13 missing, elapsed time: 3429.525
Imputing row 24801/41393 with 5 missing, elapsed time: 3429.588
Imputing row 24901/41393 with 13 missing, elapsed time: 3429.666
Imputing row 25001/41393 with 15 missing, elapsed time: 3429.775
Imputing row 25101/41393 with 8 missing, elapsed time: 3429.838
Imputing row 25201/41393 with 16 missing, elapsed time: 3429.916
Imputing row 25301/41393 with 14 missing, elapsed time: 3429.979
Imputing row 25401/41393 with 12 missing, elapsed time: 3430.041
Imputing row 25501/41393 with 7 missing, elapsed time: 3430.135
Imputing row 25601/41393 with 7 missing, elapsed time: 3430.197
Imputing row 25701/41393 with 13 missing, elapsed time: 3430.276
Imputing row 25801/41393 with 12 missing, elapsed time: 3430.369
Imputing row 25901/41393 with 12 missing, elapsed time: 3430.432
Imputing row 26001/41393 with 6 missing, elapsed time: 3430.494
Imputing row 26101/41393 with 13 missing, elapsed time: 3430.572
Imputing row 26201/41393 with 7 missing, elapsed time: 3430.635
Imputing row 26301/41393 with 11 missing, elapsed time: 3430.713
Imputing row 26401/41393 with 14 missing, elapsed time: 3430.776
Imputing row 26501/41393 with 16 missing, elapsed time: 3430.869
Imputing row 26601/41393 with 9 missing, elapsed time: 3430.947
Imputing row 26701/41393 with 8 missing, elapsed time: 3431.027
Imputing row 26801/41393 with 13 missing, elapsed time: 3431.088
Imputing row 26901/41393 with 12 missing, elapsed time: 3431.166
Imputing row 27001/41393 with 5 missing, elapsed time: 3431.213
Imputing row 27101/41393 with 8 missing, elapsed time: 3431.291
Imputing row 27201/41393 with 5 missing, elapsed time: 3431.354
Imputing row 27301/41393 with 6 missing, elapsed time: 3431.432
Imputing row 27401/41393 with 14 missing, elapsed time: 3431.494
Imputing row 27501/41393 with 9 missing, elapsed time: 3431.572
Imputing row 27601/41393 with 17 missing, elapsed time: 3431.666
Imputing row 27701/41393 with 11 missing, elapsed time: 3431.744
Imputing row 27801/41393 with 2 missing, elapsed time: 3431.885
Imputing row 27901/41393 with 5 missing, elapsed time: 3431.947
Imputing row 28001/41393 with 14 missing, elapsed time: 3432.026
Imputing row 28101/41393 with 6 missing, elapsed time: 3432.088
Imputing row 28201/41393 with 9 missing, elapsed time: 3432.166
Imputing row 28301/41393 with 15 missing, elapsed time: 3432.229
Imputing row 28401/41393 with 9 missing, elapsed time: 3432.291
Imputing row 28501/41393 with 10 missing, elapsed time: 3432.369
Imputing row 28601/41393 with 7 missing, elapsed time: 3432.416
Imputing row 28701/41393 with 8 missing, elapsed time: 3432.494
Imputing row 28801/41393 with 7 missing, elapsed time: 3432.557
Imputing row 28901/41393 with 5 missing, elapsed time: 3432.619
Imputing row 29001/41393 with 12 missing, elapsed time: 3432.682
Imputing row 29101/41393 with 5 missing, elapsed time: 3432.744
Imputing row 29201/41393 with 11 missing, elapsed time: 3432.822
Imputing row 29301/41393 with 11 missing, elapsed time: 3432.901
Imputing row 29401/41393 with 9 missing, elapsed time: 3432.979
Imputing row 29501/41393 with 17 missing, elapsed time: 3433.057
Imputing row 29601/41393 with 17 missing, elapsed time: 3433.119
Imputing row 29701/41393 with 8 missing, elapsed time: 3433.182
Imputing row 29801/41393 with 6 missing, elapsed time: 3433.244
Imputing row 29901/41393 with 12 missing, elapsed time: 3433.307
Imputing row 30001/41393 with 18 missing, elapsed time: 3433.385
Imputing row 30101/41393 with 6 missing, elapsed time: 3433.447
Imputing row 30201/41393 with 6 missing, elapsed time: 3433.526
Imputing row 30301/41393 with 9 missing, elapsed time: 3433.604
Imputing row 30401/41393 with 13 missing, elapsed time: 3433.682
Imputing row 30501/41393 with 11 missing, elapsed time: 3433.744
Imputing row 30601/41393 with 8 missing, elapsed time: 3433.854
Imputing row 30701/41393 with 14 missing, elapsed time: 3433.916
Imputing row 30801/41393 with 9 missing, elapsed time: 3434.010
Imputing row 30901/41393 with 6 missing, elapsed time: 3434.072
Imputing row 31001/41393 with 5 missing, elapsed time: 3434.135
Imputing row 31101/41393 with 18 missing, elapsed time: 3434.229
Imputing row 31201/41393 with 5 missing, elapsed time: 3434.307
Imputing row 31301/41393 with 8 missing, elapsed time: 3434.369
Imputing row 31401/41393 with 17 missing, elapsed time: 3434.447
Imputing row 31501/41393 with 10 missing, elapsed time: 3434.510
Imputing row 31601/41393 with 8 missing, elapsed time: 3434.588
Imputing row 31701/41393 with 6 missing, elapsed time: 3434.666
Imputing row 31801/41393 with 5 missing, elapsed time: 3434.729
Imputing row 31901/41393 with 28 missing, elapsed time: 3434.791
Imputing row 32001/41393 with 19 missing, elapsed time: 3434.838
Imputing row 32101/41393 with 4 missing, elapsed time: 3434.916
Imputing row 32201/41393 with 3 missing, elapsed time: 3434.994
Imputing row 32301/41393 with 12 missing, elapsed time: 3435.088
Imputing row 32401/41393 with 11 missing, elapsed time: 3435.151
Imputing row 32501/41393 with 8 missing, elapsed time: 3435.213
Imputing row 32601/41393 with 9 missing, elapsed time: 3435.276
Imputing row 32701/41393 with 12 missing, elapsed time: 3435.354
Imputing row 32801/41393 with 4 missing, elapsed time: 3435.432
Imputing row 32901/41393 with 26 missing, elapsed time: 3435.494
Imputing row 33001/41393 with 16 missing, elapsed time: 3435.572
Imputing row 33101/41393 with 2 missing, elapsed time: 3435.635
Imputing row 33201/41393 with 15 missing, elapsed time: 3435.698
Imputing row 33301/41393 with 11 missing, elapsed time: 3435.776
Imputing row 33401/41393 with 12 missing, elapsed time: 3435.854
Imputing row 33501/41393 with 5 missing, elapsed time: 3435.916
Imputing row 33601/41393 with 11 missing, elapsed time: 3435.979
Imputing row 33701/41393 with 8 missing, elapsed time: 3436.057
Imputing row 33801/41393 with 5 missing, elapsed time: 3436.135
Imputing row 33901/41393 with 12 missing, elapsed time: 3436.213
Imputing row 34001/41393 with 8 missing, elapsed time: 3436.401
Imputing row 34101/41393 with 6 missing, elapsed time: 3436.463
Imputing row 34201/41393 with 11 missing, elapsed time: 3436.526
Imputing row 34301/41393 with 9 missing, elapsed time: 3436.604
Imputing row 34401/41393 with 13 missing, elapsed time: 3436.666
Imputing row 34501/41393 with 20 missing, elapsed time: 3436.729
Imputing row 34601/41393 with 6 missing, elapsed time: 3436.807
Imputing row 34701/41393 with 15 missing, elapsed time: 3436.885
Imputing row 34801/41393 with 9 missing, elapsed time: 3436.979
Imputing row 34901/41393 with 12 missing, elapsed time: 3437.041
Imputing row 35001/41393 with 10 missing, elapsed time: 3437.119
Imputing row 35101/41393 with 5 missing, elapsed time: 3437.198
Imputing row 35201/41393 with 8 missing, elapsed time: 3437.260
Imputing row 35301/41393 with 11 missing, elapsed time: 3437.323
Imputing row 35401/41393 with 12 missing, elapsed time: 3437.401
Imputing row 35501/41393 with 10 missing, elapsed time: 3437.463
Imputing row 35601/41393 with 7 missing, elapsed time: 3437.541

Imputing row 35701/41393 with 13 missing, elapsed time: 3437.619
Imputing row 35801/41393 with 28 missing, elapsed time: 3437.682
Imputing row 35901/41393 with 12 missing, elapsed time: 3437.760
Imputing row 36001/41393 with 12 missing, elapsed time: 3437.838
Imputing row 36101/41393 with 17 missing, elapsed time: 3437.901
Imputing row 36201/41393 with 3 missing, elapsed time: 3437.963
Imputing row 36301/41393 with 13 missing, elapsed time: 3438.026
Imputing row 36401/41393 with 10 missing, elapsed time: 3438.104
Imputing row 36501/41393 with 12 missing, elapsed time: 3438.166
Imputing row 36601/41393 with 13 missing, elapsed time: 3438.244
Imputing row 36701/41393 with 14 missing, elapsed time: 3438.369
Imputing row 36801/41393 with 12 missing, elapsed time: 3438.432
Imputing row 36901/41393 with 4 missing, elapsed time: 3438.541
Imputing row 37001/41393 with 5 missing, elapsed time: 3438.604
Imputing row 37101/41393 with 12 missing, elapsed time: 3438.682
Imputing row 37201/41393 with 6 missing, elapsed time: 3438.729
Imputing row 37301/41393 with 8 missing, elapsed time: 3438.807
Imputing row 37401/41393 with 13 missing, elapsed time: 3438.885
Imputing row 37501/41393 with 14 missing, elapsed time: 3438.948
Imputing row 37601/41393 with 4 missing, elapsed time: 3439.041
Imputing row 37701/41393 with 18 missing, elapsed time: 3439.119
Imputing row 37801/41393 with 5 missing, elapsed time: 3439.198
Imputing row 37901/41393 with 4 missing, elapsed time: 3439.276
Imputing row 38001/41393 with 5 missing, elapsed time: 3439.338
Imputing row 38101/41393 with 3 missing, elapsed time: 3439.432
Imputing row 38201/41393 with 16 missing, elapsed time: 3439.510
Imputing row 38301/41393 with 12 missing, elapsed time: 3439.573
Imputing row 38401/41393 with 7 missing, elapsed time: 3439.651
Imputing row 38501/41393 with 6 missing, elapsed time: 3439.729
Imputing row 38601/41393 with 4 missing, elapsed time: 3439.776
Imputing row 38701/41393 with 6 missing, elapsed time: 3439.854
Imputing row 38801/41393 with 18 missing, elapsed time: 3439.916
Imputing row 38901/41393 with 10 missing, elapsed time: 3439.979
Imputing row 39001/41393 with 6 missing, elapsed time: 3440.057
Imputing row 39101/41393 with 9 missing, elapsed time: 3440.135
Imputing row 39201/41393 with 10 missing, elapsed time: 3440.198
Imputing row 39301/41393 with 11 missing, elapsed time: 3440.276
Imputing row 39401/41393 with 10 missing, elapsed time: 3440.354
Imputing row 39501/41393 with 7 missing, elapsed time: 3440.416
Imputing row 39601/41393 with 7 missing, elapsed time: 3440.494
Imputing row 39701/41393 with 11 missing, elapsed time: 3440.557
Imputing row 39801/41393 with 7 missing, elapsed time: 3440.604
Imputing row 39901/41393 with 18 missing, elapsed time: 3440.651
Imputing row 40001/41393 with 16 missing, elapsed time: 3440.698
Imputing row 40101/41393 with 6 missing, elapsed time: 3440.744
Imputing row 40201/41393 with 18 missing, elapsed time: 3440.791
Imputing row 40301/41393 with 13 missing, elapsed time: 3440.838
Imputing row 40401/41393 with 8 missing, elapsed time: 3440.901
Imputing row 40501/41393 with 9 missing, elapsed time: 3440.948
Imputing row 40601/41393 with 15 missing, elapsed time: 3440.994
Imputing row 40701/41393 with 15 missing, elapsed time: 3441.041
Imputing row 40801/41393 with 17 missing, elapsed time: 3441.104
Imputing row 40901/41393 with 14 missing, elapsed time: 3441.151
Imputing row 41001/41393 with 9 missing, elapsed time: 3441.213
Imputing row 41101/41393 with 24 missing, elapsed time: 3441.260
Imputing row 41201/41393 with 14 missing, elapsed time: 3441.307
Imputing row 41301/41393 with 11 missing, elapsed time: 3441.369
[KNN] Warning: 47978/6374522 still missing after imputation, replacing with 0

In [41]:
# If those weird percentage shows up, rerun the top saved cells. 


connect_2 = connect_2.reset_index(drop=True)
connect = connect.reset_index(drop=True)

connect_3 = pd.concat((connect, connect_2),axis=1).copy()

connect_3 = pd.concat((saved[["tic","Target","public_date"]],connect_3),axis=1)

connect_3 = connect_3.groupby('tic').apply(lambda group: group.iloc[1:, 1:]).reset_index()

connect_3 = connect_3.drop(["level_1"],axis=1)

full_3 = pd.merge(connect_3,bank_dp,left_on="tic",right_on="Ticker",how="left")

connect_3 = connect_3.drop(['tic'],axis=1)


connect_3.to_csv(gp+"/New/connect_correct.csv")


full_3.to_csv(gp+"/New/full_3_correct.csv")


saved.to_csv(gp+"/New/saved_1_correct.csv")

### I would run it from here: Above imputation takes too long

In [42]:
#full_3 = pd.read_csv("full_3_big.csv")
full_3 = pd.read_csv(gp+"/New/full_3_correct.csv")
full_3 = full_3.ix[:,1:]
connect_3 = full_3.drop(bank_dp.columns,axis=1)

"""
connect_3 = pd.read_csv("connect_3_big.csv")
connect_3 = connect_3.ix[:,1:]
connect_3.shape
"""

#saved = pd.read_csv("saved_1_big.csv")
saved = pd.read_csv(gp+"/New/saved_1_correct.csv")
saved = saved.ix[:,1:]

connect_3["Target"].value_counts()

connect_3[connect_3["Target"]==1].shape

saved[saved["Target"]==1].shape

connect_3 = connect_3.reset_index(drop=True)
connect_3["Target"] = connect_3["Target"].apply(lambda x: 0 if (x==1) else 1)
saved["Target"] = saved["Target"].apply(lambda x: 0 if (x==1) else 1)


saved['public_date'] = saved['public_date'].apply(lambda x: parse(str(x)))

saved = saved.sort_values("public_date").reset_index()

connect_3['public_date'] = connect_3['public_date'].apply(lambda x: parse(str(x)))

connect_3 = connect_3.sort_values("public_date").reset_index(drop=True)



connect_3.shape

(33267, 311)

In [48]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import roc_auc_score
from sklearn.cross_validation import cross_val_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import KFold
import xgboost

full_sample = True

if full_sample == True:
    final = connect_3.copy()
    
    #final = final.drop("public_date",axis=1)
    
else:
    # Delete if all ********
    print("One")
    final = pd.DataFrame()
    blue = saved[saved["Target"]==1].reset_index(drop=True).copy()
    connect_4 = connect_3.drop(['public_date'],axis=1)
    red = connect_4[connect_4["Target"]==1].reset_index(drop=True).copy().reset_index(drop=True)

    final_das = pd.concat((blue[["tic","public_date"]],red),axis=1)

    final_one = final_das.groupby(['tic']).tail(1).reset_index(drop=True)

    blue = saved[saved["Target"]==0].reset_index(drop=True).copy()
    red = connect_4[connect_4["Target"]==0].reset_index(drop=True).copy()

    final_two = pd.concat((blue[["tic","public_date"]],red),axis=1).reset_index(drop=True)

    final = pd.concat((final_one, final_two ),axis=0).reset_index(drop=True)

    final = final.reset_index(drop=True)

    final = final.sort_values("public_date").reset_index(drop=True)

    #final = final[np.isfinite(final['Target'])]
    
    final = final[~final["Target"].isnull()].reset_index(drop=True)
    
    final = final.drop("tic",axis=1)
    
    final = final.reset_index(drop=True)
    

    
    
final = final.rename(columns={'at_x': 'at', 'at_x_prtc': 'at_prtc'})

final["public_date"] = final["public_date"].apply(lambda x: parse(str(x)))

tscv = TimeSeriesSplit(n_splits=10)

#kf = KFold(n_splits=10,random_state=1000) 

#print(tscv) 
aDict = {}
dit= -2
dit = dit +1


log = pd.DataFrame()

# This X up here is just for show, the real X is down there
X = final.drop(["tic","Target","sic_prtc","fyear_x","naics_prtc","fyear_x_prtc","fyear_y_prtc","dlrsn","dldte","fyear_y","apdedate","at_y","fyr_x","fyr_y"],axis=1)
X = X.drop(["sic","naics","dlrsn_prtc","dldte_prtc","cik_prtc","apdedate_prtc","at_y_prtc","fyr_x_prtc","fyr_y_prtc","cik","emol","emol_prtc"],axis=1)



i = 0
for train_index, test_index in tscv.split(X):
#for train_index, test_index in kf.split(X):
    
    dit = dit +1




    import xgboost as xgb
    from xgboost.sklearn import XGBClassifier
    

    y = final["Target"]
    
    print(y.value_counts())


    X = final.drop(["tic","Target","sic_prtc","fyear_x","naics_prtc","fyear_x_prtc","fyear_y_prtc","dlrsn","dldte","fyear_y","apdedate","at_y","fyr_x","fyr_y"],axis=1)
    X = X.drop(["sic","naics","dlrsn_prtc","dldte_prtc","cik_prtc","apdedate_prtc","at_y_prtc","fyr_x_prtc","fyr_y_prtc","cik","emol","emol_prtc"],axis=1)


    X_train, X_test = X.ix[train_index,:], X.ix[test_index,:]
    y_train, y_test = y[train_index], y[test_index]
          
    print(X_train["public_date"].max())
    print(X_train["public_date"].min())
    high_tr = X_train["public_date"].max()
    low_tr =  X_train["public_date"].min()
    train_per =  str(low_tr)  + "-" + str(high_tr)
    
    print(X_test["public_date"].max())
    print(X_test["public_date"].min())
    high_te = X_test["public_date"].max()
    low_te =  X_test["public_date"].min()
    test_per = str(low_te) + "-" + str(high_te) 
          
          
    X_train = X_train.drop(["public_date"],axis=1)
    X_test = X_test.drop(["public_date"],axis=1)
    X = X.drop(["public_date"],axis=1)      
          

    print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

    #X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)


    y_train = list(y_train.values)
    y_test = list(y_test.values)


    clf = XGBClassifier(
                          max_depth=12,
                          objective= 'binary:logistic', 
                          silent=0, 
                          seed=29,
                          nthread= 1,
                          n_estimators= 200,
                          min_child_weight= 0,
                          learning_rate= 0.1,
                          colsample_bytree= 0.2,
                          subsample= 0.8
    )

    # 5000, 200

    """
        clf = XGBClassifier(
                          max_depth=7,
                          objective= 'binary:logistic', 
                          silent=1, 
                          seed=29)
    """

    i = i +1
    framed = np.array
    
    dit = dit +1

    clf.fit(X_train, y_train)



    from sklearn.metrics import roc_auc_score
    from sklearn.metrics import average_precision_score
    from sklearn.metrics import confusion_matrix
    from sklearn.metrics import log_loss, accuracy_score
    from sklearn.metrics import brier_score_loss

    #clf = pickle.load(open("banker.sav", 'rb'))
    #clf = pickle.load(open("banker_2Y.sav", 'rb'))

    #clf = pickle.load(open("banker_time.sav", 'rb'))


    #clf = pickle.load(open("banker_1Y.sav", 'rb'))

    y_predict = clf.predict(X_test)
    y_predict_prob = clf.predict_proba(X_test)
    #print metrics.accuracy_score(y_test, y_predict)


    gb = pd.DataFrame({'score':clf.feature_importances_, 'feature':X.columns.values})

    #bm, nopiq, intanq, niq,adjex, piq, oibdpq
    gb = gb.sort_values("score",ascending=False).head(1000).reset_index(drop=True)

    print(classification_report(y_test, y_predict))

    # Connect These 
    rat = pd.read_excel(gp+"\Trackers\\ratio_tracker.xlsx")
    act = pd.read_excel(gp+"\Trackers\\acc_tracker.xlsx")


    act = act[["Variable Name","Variable Description","Category"]]
    rat = rat[["Variable Name","Financial Ratio","Category"]]
    rat["Variable Description"] = rat["Financial Ratio"]
    rat.drop("Financial Ratio",axis=1, inplace=True)

    act["Type"] = "Fixed Value"
    rat["Type"] = "Ratio"

    ract = pd.concat((act,rat),axis=0).reset_index(drop=True)
    ract["Period"] = "Fixed Period"

    #ract.loc[ract.shape[0]+1] = ["optprcey","Options Outstanding End of Year - Price"]
    #ract.loc[ract.shape[0]+1] = ["stkco","Stock Compensation Expense"]
    #ract.loc[ract.shape[0]+1] = ["xintopt","Implied Option Expense"]

    ract_pct = pd.DataFrame()
    ract_pct["Variable Name"] = ract["Variable Name"].apply(lambda x: x+"_prtc" )
    ract_pct["Variable Description"] = ract["Variable Description"].apply(lambda x: "% Change in "+x)
    ract_pct["Category"] = ract["Category"]
    ract_pct["Type"] = ract["Type"]
    ract_pct["Period"] = "% Change"

    blackt = pd.concat((ract,ract_pct),axis=0)


    gb = pd.merge(gb, blackt, left_on="feature", right_on="Variable Name", how="left")

    confusion_mat = confusion_matrix(y_test,y_predict)

    TN = confusion_mat[0][0]
    FP = confusion_mat[0][1]
    TP = confusion_mat[1][1]
    FN = confusion_mat[1][0]

    TPR = TP/(TP+FN)
    # Specificity or true negative rate
    TNR = TN/(TN+FP) 
    # Precision or positive predictive value
    PPV = TP/(TP+FP)
    # Negative predictive value
    NPV = TN/(TN+FN)
    # Fall out or false positive rate
    FPR = FP/(FP+TN)
    # False negative rate
    FNR = FN/(TP+FN)
    # False discovery rate
    FDR = FP/(TP+FP)
    
    

    ll = log_loss(y_test, y_predict_prob) # Its low but means nothing to me. 
    print(ll)
    br = brier_score_loss(y_test, y_predict_prob[:,1]) # Its low but means nothing to me. 
    print(br) # very similar to false discovery rate. So your fine. 
    acc = accuracy_score(y_test, y_predict)
    print(acc)
    auc = roc_auc_score(y_test, y_predict_prob[:,1])
    print(auc)
    prc = average_precision_score(y_test, y_predict_prob[:,1]) 
    print(prc) # This is a useless measure

    print("Bankrupt")
    print(PPV)
    print(FPR)
    print(FDR)

    print("Healthy")
    print(NPV)
    print(FNR)


    #9604 - Three
    #9172 - One
    #Accuracy AUC and Errors an Confusion matrix with Percentages. 


    # Second Type
    
    data = np.array([np.arange(1)]*1).T

    df_exec = pd.DataFrame(data)

    df_exec["Average Log Likelihood"] = ll
    df_exec["Brier Score Loss"] = br
    df_exec["Accuracy Score"] = acc
    df_exec["ROC AUC Sore"] = auc
    df_exec["Average Precision Score"] = prc
    df_exec["Precision - Bankrupt Firms"] = PPV
    df_exec["False Positive Rate (p-value)"] = FPR
    df_exec["Precision - Healthy Firms"] = NPV
    df_exec["False Negative Rate (recall error)"] = FNR
    df_exec["False Discovery Rate "] = FDR
    df_exec["All Observations"] = TN + TP + FN + FP

    df_exec["Bankruptcy Sample"] = TP + FN
    df_exec["Healthy Sample"] = TN + FP

    df_exec["Recalled Bankruptcy"] = TP + FP
    df_exec["Correct (True Positives)"] = TP
    df_exec["Incorrect (False Positives)"] = FP

    df_exec["Recalled Healthy"] = TN + FN
    df_exec["Correct (True Negatives)"] = TN
    df_exec["Incorrect (False Negatives)"] = FN
    df_exec["Train Period"] = train_per
    df_exec["Test Period"] = test_per


    #df_exec = df_exec.T


    log = log.append(df_exec)

0    32029
1     1238
Name: Target, dtype: int64
1989-12-31 00:00:00
1977-06-30 00:00:00
1994-06-30 00:00:00
1989-12-31 00:00:00
(3027, 284) (3024, 284) (3027,) (3024,)

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

             precision    recall  f1-score   support

          0       0.97      0.99      0.98      2918
          1       0.57      0.25      0.35       106

avg / total       0.96      0.97      0.96      3024

0.10058064393643587
0.025566160806115873
0.9672619047619048
0.9398108034709739
0.46388631114207923
Bankrupt
0.574468085106383
0.006854009595613434
0.425531914893617
Healthy
0.9734632180047027
0.7452830188679245
0    32029
1     1238
Name: Target, dtype: int64
1994-06-30 00:00:00
1977-06-30 00:00:00
1995-12-31 00:00:00
1994-06-30 00:00:00
(6051, 284) (3024, 284) (6051,) (3024,)

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

             precision    recall  f1-score   support

          0       0.99      1.00      1.00      2996
          1       0.90      0.32      0.47        28

avg / total       0.99      0.99      0.99      3024

0.026993092657430825
0.006127662893168728
0.9933862433862434
0.9650963189013924
0.5373519694551873
Bankrupt
0.9
0.0003337783711615487
0.1
Healthy
0.9936960849369608
0.6785714285714286
0    32029
1     1238
Name: Target, dtype: int64
1995-12-31 00:00:00
1977-06-30 00:00:00
2001-05-31 00:00:00
1995-12-31 00:00:00
(9075, 284) (3024, 284) (9075,) (3024,)

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

             precision    recall  f1-score   support

          0       0.89      1.00      0.94      2661
          1       0.86      0.14      0.24       363

avg / total       0.89      0.89      0.86      3024

0.442853092723233
0.09082757461020032
0.8941798941798942
0.9187514170090781
0.6701397308311065
Bankrupt
0.864406779661017
0.003006388575723412
0.13559322033898305
Healthy
0.8947723440134907
0.859504132231405
0    32029
1     1238
Name: Target, dtype: int64
2001-05-31 00:00:00
1977-06-30 00:00:00
2003-12-31 00:00:00
2001-05-31 00:00:00
(12099, 284) (3024, 284) (12099,) (3024,)

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

             precision    recall  f1-score   support

          0       0.98      0.99      0.99      2905
          1       0.68      0.55      0.61       119

avg / total       0.97      0.97      0.97      3024

0.09162804948316303
0.022111410395665654
0.9722222222222222
0.9553074241744891
0.64015858121822
Bankrupt
0.6804123711340206
0.010671256454388985
0.31958762886597936
Healthy
0.981892722924496
0.44537815126050423
0    32029
1     1238
Name: Target, dtype: int64
2003-12-31 00:00:00
1977-06-30 00:00:00
2004-12-31 00:00:00
2003-12-31 00:00:00
(15123, 284) (3024, 284) (15123,) (3024,)

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

             precision    recall  f1-score   support

          0       0.99      1.00      0.99      2993
          1       0.36      0.16      0.22        31

avg / total       0.98      0.99      0.99      3024

0.04162230914340385
0.009222213790164384
0.9884259259259259
0.9103607341862194
0.2837959022944826
Bankrupt
0.35714285714285715
0.003007016371533578
0.6428571428571429
Healthy
0.9913621262458472
0.8387096774193549
0    32029
1     1238
Name: Target, dtype: int64
2004-12-31 00:00:00
1977-06-30 00:00:00
2005-12-31 00:00:00
2004-12-31 00:00:00
(18147, 284) (3024, 284) (18147,) (3024,)

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

             precision    recall  f1-score   support

          0       1.00      1.00      1.00      3003
          1       0.67      0.29      0.40        21

avg / total       0.99      0.99      0.99      3024

0.02523452894293707
0.004856312398642055
0.9940476190476191
0.9309896452753594
0.5033160113650323
Bankrupt
0.6666666666666666
0.000999000999000999
0.3333333333333333
Healthy
0.9950248756218906
0.7142857142857143
0    32029
1     1238
Name: Target, dtype: int64
2005-12-31 00:00:00
1977-06-30 00:00:00
2009-12-31 00:00:00
2005-12-31 00:00:00
(21171, 284) (3024, 284) (21171,) (3024,)

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

             precision    recall  f1-score   support

          0       0.94      1.00      0.97      2805
          1       0.90      0.16      0.27       219

avg / total       0.94      0.94      0.92      3024

0.25345854124039024
0.05343891793479962
0.9378306878306878
0.9295550183543736
0.6294966164238428
Bankrupt
0.8974358974358975
0.00142602495543672
0.10256410256410256
Healthy
0.9383584589614741
0.8401826484018264
0    32029
1     1238
Name: Target, dtype: int64
2009-12-31 00:00:00
1977-06-30 00:00:00
2013-12-31 00:00:00
2009-12-31 00:00:00
(24195, 284) (3024, 284) (24195,) (3024,)

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

             precision    recall  f1-score   support

          0       0.98      1.00      0.99      2934
          1       0.62      0.26      0.36        90

avg / total       0.97      0.97      0.97      3024

0.07975954767024056
0.02043192280367874
0.9732142857142857
0.9641142164659547
0.5312159875778786
Bankrupt
0.6216216216216216
0.004771642808452625
0.3783783783783784
Healthy
0.9775694676933377
0.7444444444444445
0    32029
1     1238
Name: Target, dtype: int64
2013-12-31 00:00:00
1977-06-30 00:00:00
2014-12-31 00:00:00
2013-12-31 00:00:00
(27219, 284) (3024, 284) (27219,) (3024,)

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

             precision    recall  f1-score   support

          0       0.99      1.00      0.99      2973
          1       0.67      0.27      0.39        51

avg / total       0.98      0.99      0.98      3024

0.04893987744456496
0.011558597831596169
0.9854497354497355
0.9596960883243307
0.5347619950191193
Bankrupt
0.6666666666666666
0.0023545240497813654
0.3333333333333333
Healthy
0.9876789876789877
0.7254901960784313
0    32029
1     1238
Name: Target, dtype: int64
2014-12-31 00:00:00
1977-06-30 00:00:00
2015-12-31 00:00:00
2014-12-31 00:00:00
(30243, 284) (3024, 284) (30243,) (3024,)

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

             precision    recall  f1-score   support

          0       0.99      0.99      0.99      2986
          1       0.52      0.61      0.56        38

avg / total       0.99      0.99      0.99      3024

0.03335928721415326
0.00863021690259385
0.9880952380952381
0.9785049529382733
0.6079959343296841
Bankrupt
0.5227272727272727
0.007032819825853985
0.4772727272727273
Healthy
0.9949664429530202
0.39473684210526316

In [49]:
log

,0,Average Log Likelihood,Brier Score Loss,Accuracy Score,ROC AUC Sore,Average Precision Score,Precision - Bankrupt Firms,False Positive Rate (p-value),Precision - Healthy Firms,False Negative Rate (recall error),False Discovery Rate,All Observations,Bankruptcy Sample,Healthy Sample,Recalled Bankruptcy,Correct (True Positives),Incorrect (False Positives),Recalled Healthy,Correct (True Negatives),Incorrect (False Negatives),Train Period,Test Period
0,0,0.100581,0.025566,0.967262,0.939811,0.463886,0.574468,0.006854,0.973463,0.745283,0.425532,3024,106,2918,47,27,20,2977,2898,79,1977-06-30 00:00:00-1989-12-31 00:00:00,1989-12-31 00:00:00-1994-06-30 00:00:00
0,0,0.026993,0.006128,0.993386,0.965096,0.537352,0.900000,0.000334,0.993696,0.678571,0.100000,3024,28,2996,10,9,1,3014,2995,19,1977-06-30 00:00:00-1994-06-30 00:00:00,1994-06-30 00:00:00-1995-12-31 00:00:00
0,0,0.442853,0.090828,0.894180,0.918751,0.670140,0.864407,0.003006,0.894772,0.859504,0.135593,3024,363,2661,59,51,8,2965,2653,312,1977-06-30 00:00:00-1995-12-31 00:00:00,1995-12-31 00:00:00-2001-05-31 00:00:00
0,0,0.091628,0.022111,0.972222,0.955307,0.640159,0.680412,0.010671,0.981893,0.445378,0.319588,3024,119,2905,97,66,31,2927,2874,53,1977-06-30 00:00:00-2001-05-31 00:00:00,2001-05-31 00:00:00-2003-12-31 00:00:00
0,0,0.041622,0.009222,0.988426,0.910361,0.283796,0.357143,0.003007,0.991362,0.838710,0.642857,3024,31,2993,14,5,9,3010,2984,26,1977-06-30 00:00:00-2003-12-31 00:00:00,2003-12-31 00:00:00-2004-12-31 00:00:00
0,0,0.025235,0.004856,0.994048,0.930990,0.503316,0.666667,0.000999,0.995025,0.714286,0.333333,3024,21,3003,9,6,3,3015,3000,15,1977-06-30 00:00:00-2004-12-31 00:00:00,2004-12-31 00:00:00-2005-12-31 00:00:00
0,0,0.253459,0.053439,0.937831,0.929555,0.629497,0.897436,0.001426,0.938358,0.840183,0.102564,3024,219,2805,39,35,4,2985,2801,184,1977-06-30 00:00:00-2005-12-31 00:00:00,2005-12-31 00:00:00-2009-12-31 00:00:00
0,0,0.079760,0.020432,0.973214,0.964114,0.531216,0.621622,0.004772,0.977569,0.744444,0.378378,3024,90,2934,37,23,14,2987,2920,67,1977-06-30 00:00:00-2009-12-31 00:00:00,2009-12-31 00:00:00-2013-12-31 00:00:00
0,0,0.048940,0.011559,0.985450,0.959696,0.534762,0.666667,0.002355,0.987679,0.725490,0.333333,3024,51,2973,21,14,7,3003,2966,37,1977-06-30 00:00:00-2013-12-31 00:00:00,2013-12-31 00:00:00-2014-12-31 00:00:00
0,0,0.033359,0.008630,0.988095,0.978505,0.607996,0.522727,0.007033,0.994966,0.394737,0.477273,3024,38,2986,44,23,21,2980,2965,15,1977-06-30 00:00:00-2014-12-31 00:00:00,2014-12-31 00:00:00-2015-12-31 00:00:00