In [1]:
import pandas as pd

In [2]:
core = pd.read_csv("data/core_dataset.csv")
hr = pd.read_csv("data/HRDataset_v9.csv")
recruit = pd.read_csv("data/recruiting_costs.csv")
produce = pd.read_csv("data/production_staff.csv")
salary = pd.read_csv("data/salary_grid.csv")

In [4]:
pd.options.display.max_columns = None

In [7]:
core.shape

(302, 21)

In [14]:
hr["Department"].value_counts()

Production              208
IT/IS                    50
Sales                    31
Admin Offices            10
Software Engineering     10
Executive Office          1
Name: Department, dtype: int64

In [21]:
hr["Reason For Term"].value_counts()

N/A - still employed                197
Another position                     20
unhappy                              14
N/A - Has not started yet            11
more money                           11
career change                         9
hours                                 9
attendance                            7
relocation out of area                5
return to school                      5
retiring                              4
military                              4
performance                           4
medical issues                        3
no-call, no-show                      3
maternity leave - did not return      3
gross misconduct                      1
Name: Reason For Term, dtype: int64

In [24]:
hr.head()

,Employee Name,Employee Number,MarriedID,MaritalStatusID,GenderID,EmpStatus_ID,DeptID,Perf_ScoreID,Age,Pay Rate,State,Zip,DOB,Sex,MaritalDesc,CitizenDesc,Hispanic/Latino,RaceDesc,Date of Hire,Days Employed,Date of Termination,Reason For Term,Employment Status,Department,Position,Manager Name,Employee Source,Performance Score
0,"Brown, Mia",1103024456,1,1,0,1,1,3,30,28.50,MA,1450,11/24/1987,Female,Married,US Citizen,No,Black or African American,10/27/2008,3317,NaN,N/A - still employed,Active,Admin Offices,Accountant I,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets
1,"LaRotonda, William",1106026572,0,2,1,1,1,3,34,23.00,MA,1460,4/26/1984,Male,Divorced,US Citizen,No,Black or African American,1/6/2014,1420,NaN,N/A - still employed,Active,Admin Offices,Accountant I,Brandon R. LeBlanc,Website Banner Ads,Fully Meets
2,"Steans, Tyrone",1302053333,0,0,1,1,1,3,31,29.00,MA,2703,9/1/1986,Male,Single,US Citizen,No,White,9/29/2014,1154,NaN,N/A - still employed,Active,Admin Offices,Accountant I,Brandon R. LeBlanc,Internet Search,Fully Meets
3,"Howard, Estelle",1211050782,1,1,0,1,1,9,32,21.50,MA,2170,9/16/1985,Female,Married,US Citizen,No,White,2/16/2015,58,4/15/2015,N/A - still employed,Active,Admin Offices,Administrative Assistant,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review
4,"Singh, Nan",1307059817,0,0,0,1,1,9,30,16.56,MA,2330,5/19/1988,Female,Single,US Citizen,No,White,5/1/2015,940,NaN,N/A - still employed,Active,Admin Offices,Administrative Assistant,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review